# Databricks notebook source
# Databricks notebook source
# MAGIC %run ./01_bronze_ingestion
# MAGIC %run ./02_silver_validation
# MAGIC %run ./03_silver_tables
# MAGIC %run ./04_feature_table
# MAGIC %run ./05_train_model
# MAGIC %run ./06_fairness_audit
# MAGIC %run ./07_explanations
# MAGIC %run ./08_intervention_queue
# MAGIC %run ./09_analysis_queries
